server:
  port: 8848
  servlet:
    context-path: /yml

student:
  name: "易烊\r\n千玺"                    #字符串
  age: 21                            #数值
  gender: '男\r\n'                       #字符串
  married: false                     #布尔
  birthday: 2001/12/30 12:12:12      #日期
  info: "爱の约定"                    #字符串
  hobby: ["唱","跳","rap","篮球"]     #数组
  food:                             #集合
    - 豆腐脑
    - 包子
    - 粥
  score: {"java":100,"mysql":5,"html":110}   #Map
  car:                               #对象
    brand: byd
    color: 白
person:
  username: "玛卡巴卡"